# Generated by Django 2.2.3 on 2019-08-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=200, verbose_name='Player')),
                ('position', models.CharField(max_length=200, verbose_name='Posicion')),
                ('games', models.IntegerField(max_length=200, verbose_name='Games')),
                ('win_rate', models.CharField(max_length=200, verbose_name='Win_Rate')),
                ('kda', models.IntegerField(max_length=200, verbose_name='KDA')),
                ('avg_kills', models.IntegerField(max_length=200, verbose_name='AVG_Kills')),
                ('avg_deaths', models.IntegerField(max_length=200, verbose_name='AVG_Deaths')),
                ('avg_assists', models.IntegerField(max_length=200, verbose_name='AVG_Assists')),
                ('csm', models.IntegerField(max_length=200, verbose_name='CSM')),
                ('gpm', models.IntegerField(max_length=200, verbose_name='GPM')),
                ('dmg', models.IntegerField(max_length=200, verbose_name='DMG')),
                ('avg_dpm', models.IntegerField(max_length=200, verbose_name='AVG_DPM')),
                ('vspm', models.IntegerField(max_length=200, verbose_name='VSPM')),
                ('avg_wpm', models.IntegerField(max_length=200, verbose_name='AVG_WPM')),
                ('avg_wcpm', models.IntegerField(max_length=200, verbose_name='AVG_WCPM')),
                ('avg_vwpm', models.IntegerField(max_length=200, verbose_name='AVG_VWPM')),
                ('gd15', models.CharField(max_length=200, verbose_name='GD15')),
                ('csd15', models.CharField(max_length=200, verbose_name='CSD15')),
                ('xpd15', models.CharField(max_length=200, verbose_name='XPD15')),
                ('fb', models.CharField(max_length=200, verbose_name='FB')),
                ('fb_victim', models.CharField(max_length=200, verbose_name='FB_Victim')),
                ('penta_kills', models.IntegerField(max_length=200, verbose_name='Penta_Kills')),
                ('solo_kills', models.IntegerField(max_length=200, verbose_name='Solo_Kills')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tittle',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion'),
        ),
    ]
