# Generated by Django 2.2.3 on 2019-08-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_auto_20190813_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='avg_assists',
            field=models.TextField(db_column='AVG_Assists', null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='avg_deaths',
            field=models.TextField(db_column='AVG_Deaths', null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='avg_dpm',
            field=models.IntegerField(blank=True, db_column='AVG_DPM'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='avg_kills',
            field=models.TextField(db_column='AVG_Kills', null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='avg_vwpm',
            field=models.TextField(blank=True, db_column='AVG_VWPM'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='avg_wcpm',
            field=models.TextField(blank=True, db_column='AVG_WCPM'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='avg_wpm',
            field=models.TextField(blank=True, db_column='AVG_WPM'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='csd15',
            field=models.IntegerField(blank=True, db_column='CSD15'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='csm',
            field=models.TextField(blank=True, db_column='CSM'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='dmg',
            field=models.TextField(blank=True, db_column='DMG'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='fb',
            field=models.TextField(blank=True, db_column='FB'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='fb_victim',
            field=models.TextField(blank=True, db_column='FB_Victim'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='games',
            field=models.IntegerField(blank=True, db_column='Games'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='gd15',
            field=models.IntegerField(blank=True, db_column='GD15'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='gpm',
            field=models.IntegerField(blank=True, db_column='GPM'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='kda',
            field=models.TextField(blank=True, db_column='KDA'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='penta_kills',
            field=models.IntegerField(blank=True, db_column='Penta_Kills'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='player',
            field=models.TextField(blank=True, db_column='Player'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='position',
            field=models.TextField(blank=True, db_column='Position'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='solo_kills',
            field=models.IntegerField(blank=True, db_column='Solo_Kills'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='vspm',
            field=models.TextField(blank=True, db_column='VSPM'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='win_rate',
            field=models.TextField(blank=True, db_column='Win_Rate'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='xpd15',
            field=models.IntegerField(blank=True, db_column='XPD15'),
        ),
    ]
