# Generated by Django 2.2.3 on 2019-08-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_auto_20190813_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jugadores',
            new_name='Playersitos',
        ),
    ]
