# Generated by Django 2.2.3 on 2019-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_auto_20190813_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioPlayersitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.TextField(db_column='Player')),
                ('position', models.TextField(db_column='Position')),
                ('games', models.IntegerField(db_column='Games')),
                ('win_rate', models.TextField(db_column='Win_Rate')),
                ('kda', models.TextField(db_column='KDA')),
                ('avg_kills', models.TextField(blank=True, db_column='AVG_Kills', null=True)),
                ('avg_deaths', models.TextField(blank=True, db_column='AVG_Deaths', null=True)),
                ('avg_assists', models.TextField(blank=True, db_column='AVG_Assists', null=True)),
                ('csm', models.TextField(db_column='CSM')),
                ('gpm', models.IntegerField(db_column='GPM')),
                ('dmg', models.TextField(db_column='DMG')),
                ('avg_dpm', models.IntegerField(db_column='AVG_DPM')),
                ('vspm', models.TextField(db_column='VSPM')),
                ('avg_wpm', models.TextField(db_column='AVG_WPM')),
                ('avg_wcpm', models.TextField(db_column='AVG_WCPM')),
                ('avg_vwpm', models.TextField(db_column='AVG_VWPM')),
                ('gd15', models.IntegerField(db_column='GD15')),
                ('csd15', models.IntegerField(db_column='CSD15')),
                ('fb', models.TextField(db_column='FB')),
                ('fb_victim', models.TextField(db_column='FB_Victim')),
                ('penta_kills', models.IntegerField(db_column='Penta_Kills')),
                ('solo_kills', models.IntegerField(db_column='Solo_Kills')),
                ('xpd15', models.IntegerField(db_column='XPD15')),
            ],
        ),
        migrations.DeleteModel(
            name='Playersitos',
        ),
    ]
