# Generated by Django 2.2.3 on 2019-08-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_auto_20190816_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortafolioPlayersitos',
            new_name='Players',
        ),
    ]
