# Generated by Django 2.2.3 on 2019-08-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_auto_20190816_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='avg_dpm',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='csd15',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='games',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='gd15',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='gpm',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='penta_kills',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='solo_kills',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='xpd15',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
